### ISSUE TITLE
Error on device update in HA 0.116

### ISSUE THREAD

**Issue by Spirituss** [kkuryshev/home_assistant#3]
I receive the next error log since upgrade to Home Assistant 0.116:

```
2020-10-08 23:38:30 ERROR (MainThread) [homeassistant.components.sensor] mosportal: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 346, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 469, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/mosportal/sensor.py", line 83, in async_update
    self._state, self.update_time = await self.async_fetch_state()
TypeError: cannot unpack non-iterable NoneType object
2020-10-08 23:38:30 ERROR (MainThread) [homeassistant.components.sensor] mosportal: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 346, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 469, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/mosportal/sensor.py", line 83, in async_update
    self._state, self.update_time = await self.async_fetch_state()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by kkuryshev** [comment]
Ошибка сохраняется и после перезагрузки has?

**Comment by Spirituss** [comment]
Ошибка в логе ушла, но сенсоры отображают только даты следующей поверки счетчиков и все, остальное недоступно.

**Comment by kkuryshev** [comment]
А что в логах? Можете понизить логгирование 
```
  mosportal: debug
  mosportal.session: debug
  mosenergosbyt: debug
```
и перезапустить hass. Посмотреть в логах доп/инфу, что может быть не так. Я сам пока до 106 не обновлялся. Попозже попробую проверить на тестовой сборке.

**Comment by Spirituss** [comment]
Поставил - в логе все норм, отчитался, что подключен к порталу и данные успешно скачаны. Похоже, синтаксис на портале изменился. Все, что касается поверки и счета/оплаты - отображает. Все, что касается показаний воды - недоступно.

**Comment by kkuryshev** [comment]
Сейчас проверил на 105.2 (я так и не обновился). Данные приходят норм (только что изменил значения воды через портал Москвы). Значит скорее всего дело не в изменении апи с стороны моспортала, так как тогда бы и на 105 версии HASS тоже перестало работать. Очень интересно. А какая версия компонента у вас используется? В логах вот такая строка должна быть
``
[custom_components.mosportal] Используется версия модуля mosportal: 0.2.1
``

**Comment by Spirituss** [comment]
У меня такой строки вообще в логе нет ((
Еще такая ошибка вылезла:
```
WARNING (SyncWorker_11) [fake_useragent] Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 64, in get
    with contextlib.closing(urlopen(
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 164, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 120, in get_browser_versions
    html = get(
  File "/usr/local/lib/python3.8/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by Spirituss** [comment]
Обновил компонент - установил его через HACS. Указанной строки с версией в логе нет. Теперь в логе появляется только одна строка:
```
DEBUG (SyncWorker_14) [mosportal.water] запрашиваем данные с портала
```
Проблема не решилась - все также нет значений сенсоров, кроме поверки счетчика.

**Comment by kkuryshev** [comment]
хм...предлагаю списаться в телеграмме @kkuryshev.
